variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  environment:
    name: production
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - production
    - tags

build_staging:
  environment:
    name: staging
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - staging
    - tags
