stages:
  - deploy

deploy:
  stage: deploy
  script:
#    - sed -i 's/"version": "[0-9].[0-9].[0-9]"/"version": "'$(date +"%Y")'.'$(date +"%m")'.'$CI_PIPELINE_IID'"/' package.json
    - export ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&refresh_token=$REFRESH_TOKEN&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
    - 'curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -X PUT -T locker_chrome_extension.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/$APP_ID"'
    - 'curl -H "Authorization: Bearer $ACCESS_TOKEN" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/$APP_ID/publish"'
  tags:
    - cs_bot
  only:
    - main
