stages:
  - build

build:
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - main
    - tags

build-staging:
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - staging
    - tags


