variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - main
    - tags

build_staging:
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_bot
  only:
    - staging
    - tags
