stages:
   - build

build:
  environment:
    name: production
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_newgen
  only:
    - production-mv3
    - tags

build_staging:
  environment:
    name: staging
  stage: build
  script:
    - cystack-deployer
  tags:
    - cs_newgen
  only:
    - dev-mv3
    - tags
